#!/usr/bin/env python3
"""Writes a shields.io endpoint-badge JSON (https://shields.io/badges/endpoint-badge)
from a `coverage json` report, the same pattern benchmark/run_benchmark.py already
uses for the precision/recall badge - one badge, one source of truth, generated by
CI, never hand-edited.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


def badge_color(percent: float) -> str:
    if percent >= 90:
        return "brightgreen"
    if percent >= 75:
        return "yellow"
    return "red"


def write_badge(coverage_json_path: Path, output_path: Path) -> float:
    """Reads a `coverage json` report and writes a shields.io badge JSON.
    Returns the percent-covered figure it read, for the caller to print/log.
    """
    data = json.loads(coverage_json_path.read_text(encoding="utf-8"))
    percent: float = data["totals"]["percent_covered"]
    badge = {
        "schemaVersion": 1,
        "label": "coverage",
        "message": f"{percent:.0f}%",
        "color": badge_color(percent),
    }
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(badge, indent=2) + "\n", encoding="utf-8")
    return percent


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Write a shields.io coverage badge from a `coverage json` report."
    )
    parser.add_argument("coverage_json", type=Path, help="Path to a coverage.py JSON report.")
    parser.add_argument("output", type=Path, help="Path to write the badge JSON to.")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    percent = write_badge(args.coverage_json, args.output)
    print(f"Wrote coverage badge ({percent:.2f}%) to {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
